### PR TITLE
Big set of changes

### PR DESCRIPTION
**Pull request by shanecelis**
Hi elm, 

Thank you for bevy-input-sequence. It's been very helpful and instructive, especially the test suite you put together.

I apologize that this PR is so big. I started working with it, and I made a macro for describing key sequences like this: `keyseq! { ctrl-A alt-B shift-C }` originally as `bevy-input-sequence-macros`, but I decided to spin it off into its own crate [keyseq](https://crates.io/crates/keyseq) once I realized I could support winit too, but it was specifically made to work in conjunction with `bevy-input-sequence`.

The biggest internal change is I switched to using a trie implementation for detecting sequences. That changes its algorithmic complexity noted in the CHANGELOG below. I had to submit a [patch](https://github.com/laysakura/trie-rs/pull/20) trie-rs for functional and performance reasons. I have not done any performance testing; however, using a trie avoids having to spawn and despawn entities during input sequence matching.

I've tried to document my changes most thoroughly in the change log, which I'll put an excerpt here:

```
### Features

- Add support for bevy v0.12
- Add key chord support
- Add `key!` and `keyseq!` macro from `keyseq` crate.
- Make controllers' sequences independent of one another.
- Add `add_input_sequence_run_if()` variant.
- Add "keymod" example that uses key chords.
- Add "run_if" example

### Refactor

- Make timeout setting more ergonomic.
- Use a trie for sequence detection.

  Changes the algorithmic complexity each tick from `O(number of key_sequences)`
  to `O(length of longest key sequence)`.

- Make `new()` generic: `new<T:Into<Act>>(inputs: [T])`

### Documentation

- Describe examples in README
- Add installation, usage, and license sections to README

### Test

- The `multiple_inputs` test is disabled.

  This test includes keyboard and controller inputs. It's not clear how to
  manage these with controller sequences being independent from one another.
```

I have put a lot of effort into the README, so I hope despite the internal changes that they all still align with your vision for this crate. 

Thank you again for the excellent crate and liberal license.

-Shane

### CODE REVIEW

**Comment by not-elm** [comment]
Thank you for the great PR!

Please wait a moment so I'll check changes.
After confirmation, i will merge then release the latest version.

**Comment by shanecelis** [comment]
Oh, if this does get merged, I'll be happy submit another PR to support bevy v0.13. I'd suggest having bevy-input-sequence v0.2.0 for bevy v0.12 and v0.3.0 for bevy v0.13 or something to that effect.

**Comment by not-elm** [comment]
I don't usually write long sentences in English, and I use machine translation, so I'm sorry if it's difficult to read.

I have checked the code and its operation.

Thank you for revising it so thoroughly that it can even remove my name from the list of authors.lol

I think the modifications themselves are excellent. In particular, "trie_rs" was implemented in such a way that it can be neatly linked with "bevy_input_sequence," which was a good learning experience.


Just one point, Act::Any is not functioning, so it needs to be resolved. (I confirmed that it does not work in examples/multiple_input.rs)

Act::Any allows input from multiple keys or buttons.
For example, in the following sequence, two patterns will be allowed: [W,D,S,A] and [D,D,S,A]
```rust
[
	Act::from(KeyCode::W) | Act::from(KeyCode::D),
	Act::from(KeyCode::D),
	Act::from(KeyCode::S),
	Act::from(KeyCode::A),
]
```

"Ord::cmp" is used to search the query "Trie::bin_search_by_children_labels", but it seems that the cause is that "Ord" is not properly implemented on the Act side.
When Impl "Ord", the key must be "Ordering::Equal" if it is in Any, otherwise it must be "Ordering::Less" or "Ordering::Greater" as shown below.
```rust
    #[test]
    fn ord_eq_if_contains_key_in_lhs(){
        let key = Act::KeyChord(Modifiers::CONTROL, KeyCode::A);
        let lhs = Act::Any(vec![key.clone()]);
        let rhs = key;
        assert_eq!(lhs.cmp(&rhs), Ordering::Equal);
    }

   #[test]
    fn ord_not_eq_if_non_contains_key_in_lhs(){
        let lhs = Act::Any(vec![Act::KeyChord(Modifiers::CONTROL, KeyCode::A)]);
        let rhs = Act::KeyChord(Modifiers::CONTROL, KeyCode::B);
        // If not Equal, `lhs` is Greater or Less? It needs to be implemented with consistency.
        assert_eq!(lhs.cmp(&rhs), Ordering::Greater);
    }
```

Alternatively, I think it would be okay to delete Act::Any itself.
I'll leave the method of correction up to you, but could you please just correct this part?

**Comment by shanecelis** [comment]
Thank you for trusting me to choose. Keeping `Any` was harder than I thought it'd be. I got it done, but I'm not sure I love how I did it: I ended up splitting `Act` into `Act` and `ActPattern`. [See here.](https://github.com/shanecelis/bevy-input-sequence/blob/act-pattern/src/act.rs) I haven't added it to this PR. I added it to a new [act-pattern](https://github.com/shanecelis/bevy-input-sequence/tree/act-pattern) branch because it feels a little unwieldly but maybe it's fine. I wanted to get your opinion before merging it into this PR.

**Comment by not-elm** [comment]
So good!

I think this implementation is fine.
If there is no problem, could you please merge it into this PR?
Thank you.

**Comment by shanecelis** [comment]
Thanks! You got it.

**Comment by not-elm** [comment]
Released version 0.2.0
https://github.com/not-elm/bevy-input-sequence/releases/tag/release-v0.2.0

Thank you for your assistance!

**Pull request merged**
